#+TITLE: Sphinx-Gallery
#+SUBTITLE: Pimp your documentation with a gallery of examples
#+AUTHOR: Óscar Nájera
#+EMAIL: najera.oscar@gmail.com
#+DATE: 25 August 2016 - EuroScipy - Erlangen
#+REVEAL_PLUGINS: (highlight notes)
#+REVEAL_TRANS: slide
#+REVEAL_THEME: serif
#+REVEAL_ROOT: https://cdn.jsdelivr.net/reveal.js/3.0.0/

#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="css/style.css" />
#+REVEAL_EXTRA_CSS: https://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css
#+REVEAL_HEAD_PREAMBLE: <link rel="stylesheet" type="text/css" href="css/style.css"/>
#+OPTIONS: toc:nil email:nil num:nil

#+BEGIN_NOTES
Hello Everyone, good afternoon.

I would like to start thanking the organizer for giving me the
oportunity to present this project and also thank Inria an
Paris-Saclay Center for data Science for sponsoring me to develop this
project.

Thus Sphinx-Gallery: Pimp your documentation with a gallery of examples.
#+END_NOTES

* What is Sphinx-Gallery ?
It's an extension that builds an HTML version of any python
script and puts it into an examples gallery.
#+BEGIN_NOTES
What is Sphinx-Gallery? Sphinx as you probably already know is our go to
package for documenting python packages and Gallery because we want to
showcase examples in our documentation.
#+END_NOTES

** You are certainly familiar with this
#+BEGIN_HTML
<iframe src="http://matplotlib.org/gallery.html" width="80%" height="600px"></iframe>
#+END_HTML
http://matplotlib.org/gallery.html
#+BEGIN_NOTES
A great example of this asset is the matplotlib documentation with its
gallery. Learning from examples is a great way to get started with a
package and quickly grasp what you can do with it.
#+END_NOTES
* Now you can have it too!!
** And Better with Sphinx-Gallery

#+ATTR_REVEAL: :frag (appear)
  - The Gallery building is completely automated. You just worry about:
    *your own code*
  - Now more double code bases: Source code and documentation are the
    same python source file
  - Your examples can be downloaded as python source files & Jupyter Notebooks
  - Visible error messages when your examples don't build correctly
  - Automatically link from your API documentation to examples using the functions
* Is someone already using it?
#+ATTR_HTML: :class logo
[[http://scikit-learn.org/dev/auto_examples/index.html][file:images/scikit-learn-logo-small.png]]
[[http://nilearn.github.io/auto_examples/index.html][file:images/nilearn-logo.png]]
[[http://scikit-image.org/docs/dev/auto_examples/][file:images/skimage-logo.png]]
[[http://www.martinos.org/mne/stable/auto_examples/index.html][file:images/mne_logo.png]]
[[http://www.pygimli.org/_examples_auto/index.html][file:images/gimli-logo.png]]
[[http://docs.astropy.org/en/stable/generated/examples/index.html][file:images/astropy-logo.png]]

#+BEGIN_NOTES
  Goaled at the nilearn and scikit-learn projects. It branched from
  those two custom gallery generators into an independent package.
  Most of the gallery development came first from original project
  developers. Now it's mostly maintained by me.
#+END_NOTES

* SHOWTIME
** Setting up your Project
#+BEGIN_SRC sh
awesome_python_project
├── doc
│   ├── conf.py
│   ├── index.rst
│   └── Makefile
├── examples
│   ├── README.txt
│   └── plot_colors.py
...
#+END_SRC

#+ATTR_REVEAL: :frag (appear)
Introduce your Gallery in *examples/README.txt*
#+ATTR_REVEAL: :frag (appear)
#+BEGIN_SRC rst
  .. _My_Gallery:

  My Gallery
  ==========

  Colormaps Examples
  ------------------

  Colormap examples using Sphinx-Gallery
#+END_SRC

** Your examples in Python

With the *plot_* prefix Sphinx-Gallery executes the script

#+BEGIN_SRC python :exports source
  # -*- coding: utf-8 -*-
  r"""
  ===============================
  Colormaps alter your perception
  ===============================

  Here I plot the function

  .. math:: f(x, y) = \sin(x) + \cos(y)

  with different colormaps.

  """

  import numpy as np
  import matplotlib.pyplot as plt

  x = np.linspace(-np.pi, np.pi, 300)
  xx, yy = np.meshgrid(x, x)
  z = np.cos(xx) + np.cos(yy)

  plt.figure()
  plt.imshow(z)

  plt.figure()
  plt.imshow(z, cmap=plt.cm.get_cmap('hot'))

  plt.figure()
  plt.imshow(z, cmap=plt.cm.get_cmap('Spectral'), interpolation='none')

  # Not needed for the Gallery.
  # Only for direct execution
  plt.show()

  ###############################################################################
  # You can define blocks in your source code
  # with interleaving prose.
  #

  print("This writes to stdout and will be displayed in the HTML file")
#+END_SRC

** Setting up Sphinx-Gallery
#+ATTR_REVEAL: :frag (appear)
Install it with:
#+ATTR_REVEAL: :frag (appear)
#+BEGIN_SRC sh
  $ pip install sphinx-gallery
#+END_SRC

#+ATTR_REVEAL: :frag (appear)
Edit the *doc/conf.py* file with
#+ATTR_REVEAL: :frag (appear)
#+BEGIN_SRC python :exports source
  import sphinx_gallery
  extensions = [
      ...
      'sphinx_gallery.gen_gallery',
      ]

  sphinx_gallery_conf = {
      # path to your examples scripts
      'examples_dirs' : '../examples',
      # path where to save gallery generated examples
      'gallery_dirs'  : 'auto_examples'}
#+END_SRC

#+ATTR_REVEAL: :frag (appear)
Build the Documentation
#+ATTR_REVEAL: :frag (appear)
#+BEGIN_SRC sh
  $ make html
#+END_SRC
** Enjoy :)

** https://sphinx-gallery.readthedocs.io
#+BEGIN_HTML
<iframe src="https://sphinx-gallery.readthedocs.io/en/latest/auto_examples/index.html" width="100%" height="600px"></iframe>
#+END_HTML
** From API to Examples
#+BEGIN_HTML
<iframe src="http://nilearn.github.io/modules/generated/nilearn.input_data.NiftiMasker.html#nilearn.input_data.NiftiMasker" width="100%" height="600px"></iframe>
#+END_HTML
http://nilearn.github.io/
* Export config                                                    :noexport:
#+BEGIN_SRC emacs-lisp :results silent :exports none
  (setq org-reveal-title-slide "

  <h1 class=\"title\">%t</h1>
  <h2 class=\"subtitle\">%s</h2>

  <h2>%a</h2>
  <h3>%e / <a href=\"http://github.com/Titan-C\">
  <i class=\"fa fa-github\" aria-hidden=\"true\"></i>
  Titan-C</a></h3>

  <h2>%d</h2>
  <p class=\"sponsor\">
  <img src=\"./images/inria-logo.jpg\" alt=\"inria-logo.jpg\" class=\"logo\" />
  <img src=\"./images/cds-logo.png\" alt=\"cds-logo.png\" />
  </p>
  ")

  (org-reveal-export-to-html)
  (rename-file "euroscipy2016.html" "index.html" t)
#+END_SRC
